from __future__ import annotations

"""
Nonlinear post-processing utilities for LOB feature-engineering output.

Current pipeline (nonlinear-only)
---------------------------------
1. positive long-tail features -> log1p(x)
2. signed long-tail features   -> asinh(x / TRAIN robust scale)
3. volatility features         -> log(x + epsilon)

Explicitly NOT included here
----------------------------
- no winsorization / winsor bounds
- no mean/std fitting
- no z-score normalization
- no z-score clipping
- no missing-value filling

The existing model-training pipeline remains responsible for train-only mean/std
normalization after these nonlinear transforms.

Every transform accepts a DataFrame and returns a DataFrame with the same columns,
column order, index, and row order. Targets/identifiers are excluded by the caller.
"""

from dataclasses import asdict, dataclass
import json
import re
from pathlib import Path
from typing import Mapping, Sequence

import numpy as np
import pandas as pd


@dataclass
class FeatureGroups:
    positive_long_tail: list[str]
    signed_long_tail: list[str]
    volatility: list[str]
    passthrough: list[str]
    binary: list[str]

    def as_dict(self) -> dict[str, list[str]]:
        return asdict(self)


def _shallow_copy(df: pd.DataFrame, copy: bool) -> pd.DataFrame:
    return df.copy(deep=False) if copy else df


def _ensure_columns(df: pd.DataFrame, cols: Sequence[str]) -> None:
    missing = [c for c in cols if c not in df.columns]
    if missing:
        raise KeyError(f"Missing columns ({len(missing)}): {missing[:30]}")


def _align_timestamp_to_series_timezone(
    value: str | pd.Timestamp,
    series_tz,
) -> pd.Timestamp:
    """Return a Timestamp comparable with a datetime Series' timezone convention.

    If the Series is timezone-aware, a naive boundary is interpreted in the same local
    timezone as the Series (e.g. Europe/London), while an aware boundary is converted
    to that timezone. If the Series is timezone-naive, an aware boundary is converted
    to UTC and then made naive so pandas never compares aware and naive timestamps.
    """
    ts = pd.Timestamp(value)
    if series_tz is not None:
        if ts.tzinfo is None:
            return ts.tz_localize(series_tz)
        return ts.tz_convert(series_tz)

    if ts.tzinfo is not None:
        return ts.tz_convert("UTC").tz_localize(None)
    return ts


def make_time_train_mask(
    df: pd.DataFrame,
    *,
    time_col: str,
    train_start: str | pd.Timestamp,
    train_end: str | pd.Timestamp,
) -> np.ndarray:
    """Boolean mask for [train_start, train_end), robust to timezone-aware timestamps.

    Example: if ``df[time_col]`` has dtype ``datetime64[ns, Europe/London]`` and
    ``train_start='2025-01-01'`` / ``train_end='2025-07-01'`` are timezone-naive,
    the boundaries are localized to Europe/London before comparison. This avoids
    ``TypeError: Invalid comparison between dtype=datetime64[ns, Europe/London] and Timestamp``.
    """
    if time_col not in df.columns:
        raise KeyError(time_col)

    t = pd.to_datetime(df[time_col], errors="coerce")
    series_tz = getattr(t.dt, "tz", None)
    start = _align_timestamp_to_series_timezone(train_start, series_tz)
    end = _align_timestamp_to_series_timezone(train_end, series_tz)

    if end <= start:
        raise ValueError("train_end must be after train_start")
    return ((t >= start) & (t < end)).to_numpy(dtype=bool, copy=False)


_TARGET_PATTERNS = (
    re.compile(r"^mid_return_t_plus_\d+$"),
    re.compile(r"^target_log_return_\d+m$"),
    re.compile(r"^target_log_return_\d+m_volnorm$"),
)


def infer_target_cols(df: pd.DataFrame) -> list[str]:
    """Detect target names generated by feature_engineering_utils.py."""
    return [c for c in df.columns if any(p.search(c) for p in _TARGET_PATTERNS)]


def infer_model_feature_cols(
    df: pd.DataFrame,
    *,
    id_cols: Sequence[str] = ("RIC", "date_dt", "bucketEnd"),
    target_cols: Sequence[str] = (),
    extra_exclude_cols: Sequence[str] = (),
) -> list[str]:
    """Numeric model features, excluding IDs/targets/caller exclusions."""
    exclude = set(id_cols) | set(target_cols) | set(extra_exclude_cols)
    return [
        c for c in df.columns
        if c not in exclude and pd.api.types.is_numeric_dtype(df[c].dtype)
    ]


_VOL_PATTERNS = (
    re.compile(r"^past_vol_\d+m$"),
    re.compile(r"^roll_realized_vol_\d+$"),
    re.compile(r"(^|_)realized_vol($|_)"),
    re.compile(r"(^|_)volatility($|_)"),
)

_SIGNED_PATTERNS = (
    re.compile(r"^ofi_level_\d+$"),
    re.compile(r"^mlofi_"),
    re.compile(r"^flow_signed_vol_"),
    re.compile(r"(^|_)signed_volume($|_)"),
    re.compile(r"(^|_)signed_vol($|_)"),
)

_POSITIVE_PATTERNS = (
    re.compile(r"^numSharesTraded"),
    re.compile(r"^(bidQty|offerQty)_\d+$"),
    re.compile(r"^(bidOrderCount|offerOrderCount)_\d+$"),
    re.compile(r"^marketCapUSD$"),
    re.compile(r"^lob_(bid|ask|total)_depth_\d+$"),
    re.compile(r"^lob_avg_(bid|ask)_order_size_\d+$"),
    re.compile(r"^lob_max_(bid|ask)_gap_bps_\d+$"),
    re.compile(r"^dyn_(bid|ask)_churn_\d+$"),
    re.compile(r"^dyn_(bid|ask)_refill_proxy_\d+$"),
    re.compile(r"^dyn_(bid|ask)_refill_ratio_\d+$"),
    re.compile(r"^lob_spread_bps$"),
    re.compile(r"^spread$"),
)

_BINARY_PATTERNS = (
    re.compile(r"^lob_is_"),
    re.compile(r"^bookIsCrossed$"),
    re.compile(r"^isClose$"),
)


def _matches_any(name: str, patterns: Sequence[re.Pattern]) -> bool:
    return any(p.search(name) is not None for p in patterns)


def infer_feature_groups(
    feature_cols: Sequence[str],
    *,
    positive_long_tail_add: Sequence[str] = (),
    signed_long_tail_add: Sequence[str] = (),
    volatility_add: Sequence[str] = (),
    passthrough_add: Sequence[str] = (),
    binary_add: Sequence[str] = (),
) -> FeatureGroups:
    """Infer mutually exclusive nonlinear-transform groups from feature names."""
    cols = list(dict.fromkeys(feature_cols))
    colset = set(cols)
    explicit = {
        "positive": set(positive_long_tail_add),
        "signed": set(signed_long_tail_add),
        "vol": set(volatility_add),
        "pass": set(passthrough_add),
        "binary": set(binary_add),
    }
    for group_name, values in explicit.items():
        unknown = values - colset
        if unknown:
            raise KeyError(f"Unknown columns in {group_name} override: {sorted(unknown)[:20]}")

    positive, signed, vol, passthrough, binary = [], [], [], [], []
    for c in cols:
        if c in explicit["pass"]:
            passthrough.append(c)
        elif c in explicit["vol"]:
            vol.append(c)
        elif c in explicit["signed"]:
            signed.append(c)
        elif c in explicit["positive"]:
            positive.append(c)
        elif c in explicit["binary"]:
            binary.append(c)
        elif _matches_any(c, _VOL_PATTERNS):
            vol.append(c)
        elif _matches_any(c, _SIGNED_PATTERNS):
            signed.append(c)
        elif _matches_any(c, _POSITIVE_PATTERNS):
            positive.append(c)
        elif _matches_any(c, _BINARY_PATTERNS):
            binary.append(c)
        else:
            passthrough.append(c)

    return FeatureGroups(positive, signed, vol, passthrough, binary)


def apply_log1p_transform(
    df: pd.DataFrame,
    cols: Sequence[str],
    *,
    copy: bool = True,
    negative_policy: str = "nan",
) -> pd.DataFrame:
    """Apply log1p to positive long-tail columns; preserve schema."""
    _ensure_columns(df, cols)
    out = _shallow_copy(df, copy)
    for c in cols:
        x = pd.to_numeric(df[c], errors="coerce").to_numpy(dtype=np.float64, copy=True)
        if negative_policy == "nan":
            x[x < 0] = np.nan
        elif negative_policy == "raise" and np.any(np.isfinite(x) & (x < 0)):
            raise ValueError(f"Negative values found in positive-long-tail feature: {c}")
        elif negative_policy not in {"nan", "raise"}:
            raise ValueError("negative_policy must be 'nan' or 'raise'")
        out[c] = np.log1p(x).astype(np.float32)
    return out


def _sample_training_values(
    x: np.ndarray,
    train_mask: np.ndarray,
    *,
    max_samples: int,
    random_state: int,
) -> np.ndarray:
    vals = np.asarray(x, dtype=np.float64)[train_mask]
    vals = vals[np.isfinite(vals)]
    if len(vals) <= max_samples:
        return vals
    rng = np.random.default_rng(random_state)
    idx = rng.choice(len(vals), size=max_samples, replace=False)
    return vals[idx]


def fit_asinh_scales(
    df: pd.DataFrame,
    cols: Sequence[str],
    train_mask: np.ndarray,
    *,
    max_samples_per_feature: int = 2_000_000,
    random_state: int = 42,
    min_scale: float = 1e-8,
) -> dict[str, float]:
    """TRAIN-only robust scale s=median(abs(x_train)) for signed asinh transforms."""
    _ensure_columns(df, cols)
    train_mask = np.asarray(train_mask, dtype=bool)
    if len(train_mask) != len(df):
        raise ValueError("train_mask length must equal DataFrame length")
    scales: dict[str, float] = {}
    for i, c in enumerate(cols):
        x = pd.to_numeric(df[c], errors="coerce").to_numpy(dtype=np.float64, copy=False)
        vals = _sample_training_values(
            x, train_mask,
            max_samples=max_samples_per_feature,
            random_state=random_state + i,
        )
        if len(vals) == 0:
            raise ValueError(f"No finite TRAIN values for signed feature: {c}")
        s = float(np.median(np.abs(vals)))
        if not np.isfinite(s) or s < min_scale:
            nonzero = np.abs(vals[np.abs(vals) > min_scale])
            s = float(np.median(nonzero)) if len(nonzero) else 1.0
        scales[c] = max(s, min_scale)
    return scales


def apply_asinh_transform(
    df: pd.DataFrame,
    cols: Sequence[str],
    scales: Mapping[str, float],
    *,
    copy: bool = True,
) -> pd.DataFrame:
    """Apply asinh(x/s) using previously fitted TRAIN scales; preserve schema."""
    _ensure_columns(df, cols)
    out = _shallow_copy(df, copy)
    for c in cols:
        if c not in scales:
            raise KeyError(f"Missing asinh scale for {c}")
        s = float(scales[c])
        if not np.isfinite(s) or s <= 0:
            raise ValueError(f"Invalid asinh scale for {c}: {s}")
        x = pd.to_numeric(df[c], errors="coerce").to_numpy(dtype=np.float64, copy=False)
        out[c] = np.arcsinh(x / s).astype(np.float32)
    return out


def apply_log_volatility_transform(
    df: pd.DataFrame,
    cols: Sequence[str],
    *,
    epsilon: float = 1e-8,
    copy: bool = True,
    negative_policy: str = "nan",
) -> pd.DataFrame:
    """Apply log(vol + epsilon) to non-negative volatility features; preserve schema."""
    _ensure_columns(df, cols)
    if epsilon <= 0:
        raise ValueError("epsilon must be > 0")
    out = _shallow_copy(df, copy)
    for c in cols:
        x = pd.to_numeric(df[c], errors="coerce").to_numpy(dtype=np.float64, copy=True)
        if negative_policy == "nan":
            x[x < 0] = np.nan
        elif negative_policy == "raise" and np.any(np.isfinite(x) & (x < 0)):
            raise ValueError(f"Negative volatility values found in {c}")
        elif negative_policy not in {"nan", "raise"}:
            raise ValueError("negative_policy must be 'nan' or 'raise'")
        out[c] = np.log(x + float(epsilon)).astype(np.float32)
    return out


def save_postprocessing_state(
    path: str | Path,
    *,
    feature_groups: FeatureGroups,
    feature_cols: Sequence[str],
    asinh_scales: Mapping[str, float],
    volatility_epsilon: float,
) -> dict:
    """Persist only parameters required by the nonlinear-only transforms."""
    state = {
        "version": 2,
        "pipeline": "nonlinear_only",
        "feature_cols": list(feature_cols),
        "feature_groups": feature_groups.as_dict(),
        "asinh_scales": {k: float(v) for k, v in asinh_scales.items()},
        "volatility_epsilon": float(volatility_epsilon),
    }
    Path(path).write_text(json.dumps(state, indent=2))
    return state


def load_postprocessing_state(path: str | Path) -> dict:
    return json.loads(Path(path).read_text())


def run_postprocessing_pipeline(
    feature_engineered_df: pd.DataFrame,
    *,
    feature_cols: Sequence[str],
    train_mask: np.ndarray,
    groups: FeatureGroups | None = None,
    max_samples_per_feature: int = 2_000_000,
    random_state: int = 42,
    volatility_epsilon: float = 1e-8,
) -> tuple[pd.DataFrame, dict]:
    """Convenience wrapper for log1p -> asinh -> log-vol only."""
    if groups is None:
        groups = infer_feature_groups(feature_cols)

    step1 = apply_log1p_transform(
        feature_engineered_df, groups.positive_long_tail, copy=True
    )
    scales = fit_asinh_scales(
        step1,
        groups.signed_long_tail,
        train_mask,
        max_samples_per_feature=max_samples_per_feature,
        random_state=random_state,
    ) if groups.signed_long_tail else {}
    step2 = apply_asinh_transform(step1, groups.signed_long_tail, scales, copy=True)
    step3 = apply_log_volatility_transform(
        step2, groups.volatility, epsilon=volatility_epsilon, copy=True
    )
    state = {
        "version": 2,
        "pipeline": "nonlinear_only",
        "feature_cols": list(feature_cols),
        "feature_groups": groups.as_dict(),
        "asinh_scales": scales,
        "volatility_epsilon": float(volatility_epsilon),
    }
    return step3, state
